# Site settings
name: WQ的技术小站
email: rjgc_wq@163.com
author: wq
url: http://www.wqblog.xyz
resume_site: http://www.wqblog.xyz
github: https://github.com/WangQi1415/
baseurl:
description: 人为镜，史为鉴!
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wangqi1415

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


